// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShopping.Data;

#nullable disable

namespace OnlineShopping.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230829162124_createDb")]
    partial class createDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "1",
                            Name = "CUSTOMER",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "2",
                            Name = "ASSISTANT",
                            NormalizedName = "ASSISTANT"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "3",
                            Name = "MANAGER",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "4",
                            ConcurrencyStamp = "4",
                            Name = "ADMIN",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "4"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineShopping.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"), 1L, 1);

                    b.Property<string>("AddressOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commune")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Provine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AddressId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            AddressOwner = "USER",
                            Commune = "Commune 1",
                            District = "District 1",
                            Provine = "Provine 1",
                            Street = "Street 1"
                        },
                        new
                        {
                            AddressId = 2,
                            AddressOwner = "REPOSITORY",
                            Commune = "Commune 2",
                            District = "District 2",
                            Provine = "Provine 2",
                            Street = "Street 2"
                        },
                        new
                        {
                            AddressId = 3,
                            AddressOwner = "SUPLIER",
                            Commune = "Commune 3",
                            District = "District 3",
                            Provine = "Provine 3",
                            Street = "Street 3"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Customer.Announcement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("UserId");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            AnnouncementId = 1,
                            Content = "Welcome to the furniture shopping website!",
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Welcome",
                            UserId = "1"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Customer.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"), 1L, 1);

                    b.Property<bool>("Anonymous")
                        .HasColumnType("bit");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FurnitureSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("VoteStar")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FurnitureSpecificationId");

                    b.HasIndex("OrderId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("OnlineShopping.Models.Customer.UserAddress", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "AddressId");

                    b.HasIndex("AddressId");

                    b.ToTable("UserAddresses");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            AddressId = 1,
                            AddressType = "USER"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Customer.Warranty", b =>
                {
                    b.Property<int>("WarrantyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarrantyId"), 1L, 1);

                    b.Property<DateTime?>("EstimatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WarrantyReasons")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("WarrantyId");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Warranties");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Chair"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Table"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Bed"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollectionId"), 1L, 1);

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CollectionId");

                    b.ToTable("Collections");

                    b.HasData(
                        new
                        {
                            CollectionId = 1,
                            CollectionName = "Collection 1"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Color", b =>
                {
                    b.Property<int>("ColorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColorId"), 1L, 1);

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ColorId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            ColorId = 1,
                            ColorName = "Red"
                        },
                        new
                        {
                            ColorId = 2,
                            ColorName = "Green"
                        },
                        new
                        {
                            ColorId = 3,
                            ColorName = "Blue"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.CustomizeFurniture", b =>
                {
                    b.Property<int>("CustomizeFurnitureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomizeFurnitureId"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomizeFurnitureName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DesiredCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.Property<int>("WoodId")
                        .HasColumnType("int");

                    b.HasKey("CustomizeFurnitureId");

                    b.HasIndex("ColorId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("WoodId");

                    b.ToTable("CustomizeFurnitures");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Furniture", b =>
                {
                    b.Property<int>("FurnitureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FurnitureId"), 1L, 1);

                    b.Property<string>("AppopriateRoom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int");

                    b.Property<string>("FurnitureName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LabelId")
                        .HasColumnType("int");

                    b.Property<int>("Like")
                        .HasColumnType("int");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<double>("VoteStar")
                        .HasColumnType("float");

                    b.HasKey("FurnitureId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("LabelId");

                    b.ToTable("Furnitures");

                    b.HasData(
                        new
                        {
                            FurnitureId = 1,
                            AppopriateRoom = "Living room",
                            CategoryId = 1,
                            CollectionId = 1,
                            FurnitureName = "Testing Furniture 1",
                            LabelId = 1,
                            Like = 100,
                            Sold = 100,
                            VoteStar = 5.0
                        },
                        new
                        {
                            FurnitureId = 2,
                            AppopriateRoom = "Bed room",
                            CategoryId = 2,
                            CollectionId = 1,
                            FurnitureName = "Testing Furniture 2",
                            LabelId = 2,
                            Like = 10,
                            Sold = 120,
                            VoteStar = 4.5
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.FurnitureSpecification", b =>
                {
                    b.Property<int>("FurnitureSpecificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FurnitureSpecificationId"), 1L, 1);

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<string>("FurnitureSpecificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("Length")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.Property<int?>("WoodId")
                        .HasColumnType("int");

                    b.HasKey("FurnitureSpecificationId");

                    b.HasIndex("ColorId");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("WoodId");

                    b.ToTable("FurnitureSpecifications");

                    b.HasData(
                        new
                        {
                            FurnitureSpecificationId = 1,
                            ColorId = 1,
                            Description = " This is testing decription",
                            FurnitureId = 1,
                            FurnitureSpecificationName = "Yellow",
                            Height = 50.0,
                            Length = 50.0,
                            Price = 50.0,
                            Width = 50.0,
                            WoodId = 1
                        },
                        new
                        {
                            FurnitureSpecificationId = 2,
                            ColorId = 2,
                            Description = " This is testing decription",
                            FurnitureId = 1,
                            FurnitureSpecificationName = "Red",
                            Height = 60.0,
                            Length = 40.0,
                            Price = 50.0,
                            Width = 50.0,
                            WoodId = 2
                        },
                        new
                        {
                            FurnitureSpecificationId = 3,
                            ColorId = 1,
                            Description = " This is testing decription",
                            FurnitureId = 2,
                            FurnitureSpecificationName = "Purple",
                            Height = 30.0,
                            Length = 70.0,
                            Price = 320.0,
                            Width = 20.0,
                            WoodId = 2
                        },
                        new
                        {
                            FurnitureSpecificationId = 4,
                            ColorId = 2,
                            Description = " This is testing decription",
                            FurnitureId = 2,
                            FurnitureSpecificationName = "Black",
                            Height = 50.0,
                            Length = 30.0,
                            Price = 120.0,
                            Width = 60.0,
                            WoodId = 1
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabelId"), 1L, 1);

                    b.Property<string>("LabelName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LabelId");

                    b.ToTable("Labels");

                    b.HasData(
                        new
                        {
                            LabelId = 1,
                            LabelName = "New"
                        },
                        new
                        {
                            LabelId = 2,
                            LabelName = "Hot Sale"
                        },
                        new
                        {
                            LabelId = 3,
                            LabelName = "Best Saller"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"), 1L, 1);

                    b.Property<DateTime?>("ActualCompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomizeFurnitureId")
                        .HasColumnType("int");

                    b.Property<double?>("ExpectedPrice")
                        .HasColumnType("float");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResultId");

                    b.HasIndex("CustomizeFurnitureId")
                        .IsUnique();

                    b.ToTable("Results");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Wood", b =>
                {
                    b.Property<int>("WoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WoodId"), 1L, 1);

                    b.Property<string>("WoodType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("WoodId");

                    b.ToTable("Woods");

                    b.HasData(
                        new
                        {
                            WoodId = 1,
                            WoodType = "Cherry"
                        },
                        new
                        {
                            WoodId = 2,
                            WoodType = "Ebony"
                        },
                        new
                        {
                            WoodId = 3,
                            WoodType = "Eucalyptus"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Gallery.CustomizeFurnitureAttachment", b =>
                {
                    b.Property<int>("CustomizeFurnitureAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomizeFurnitureAttachmentId"), 1L, 1);

                    b.Property<string>("AttachmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomizeFurnitureId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomizeFurnitureAttachmentId");

                    b.HasIndex("CustomizeFurnitureId");

                    b.ToTable("CustomizeFurnitureAttachments");
                });

            modelBuilder.Entity("OnlineShopping.Models.Gallery.FeedbackAttachment", b =>
                {
                    b.Property<int>("FeedbackAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackAttachmentId"), 1L, 1);

                    b.Property<string>("AttachmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedbackId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeedbackAttachmentId");

                    b.HasIndex("FeedbackId");

                    b.ToTable("FeedbackAttachments");
                });

            modelBuilder.Entity("OnlineShopping.Models.Gallery.FurnitureSpecificationAttachment", b =>
                {
                    b.Property<int>("FurnitureSpecificationAttachemnetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FurnitureSpecificationAttachemnetId"), 1L, 1);

                    b.Property<string>("AttachmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FurnitureSpecificationId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FurnitureSpecificationAttachemnetId");

                    b.HasIndex("FurnitureSpecificationId");

                    b.ToTable("FurnitureSpecificationAttachments");
                });

            modelBuilder.Entity("OnlineShopping.Models.Gallery.WarrantyAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttachmentId"), 1L, 1);

                    b.Property<string>("AttachmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WarrantyId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("WarrantyId");

                    b.ToTable("WarrantyAttachments");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"), 1L, 1);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.CartDetail", b =>
                {
                    b.Property<int>("CartDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartDetailId"), 1L, 1);

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("FurnitureSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartDetailId");

                    b.HasIndex("CartId");

                    b.HasIndex("FurnitureSpecificationId");

                    b.ToTable("CartDetails");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.CustomizeFurnitureOrderDetail", b =>
                {
                    b.Property<int>("CustomizeFurnitureOrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomizeFurnitureOrderDetailId"), 1L, 1);

                    b.Property<int>("CustomizeFunitureId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("CustomizeFurnitureOrderDetailId");

                    b.HasIndex("CustomizeFunitureId");

                    b.HasIndex("OrderId");

                    b.ToTable("CustomizeFurnitureOrderDetails");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.FurnitureOrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"), 1L, 1);

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<int>("FurnitureSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("FurnitureSpecificationId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderDetais");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<int?>("UsedPoint")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PaymentId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"), 1L, 1);

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            PaymentMethod = "CASH"
                        },
                        new
                        {
                            PaymentId = 2,
                            PaymentMethod = "VNPAYQR"
                        },
                        new
                        {
                            PaymentId = 3,
                            PaymentMethod = "VNBANK"
                        },
                        new
                        {
                            PaymentId = 4,
                            PaymentMethod = "INTBANK"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.Point", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointId"), 1L, 1);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("History")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalPoint")
                        .HasColumnType("int");

                    b.HasKey("PointId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Points");

                    b.HasData(
                        new
                        {
                            PointId = 1,
                            CustomerId = "1",
                            Description = "Create account successfully +500 points",
                            History = new DateTime(2023, 8, 29, 23, 21, 24, 352, DateTimeKind.Local).AddTicks(7238),
                            TotalPoint = 500
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.WishList", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"), 1L, 1);

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WishlistId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("WishLists");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.WishListDetail", b =>
                {
                    b.Property<int>("WishListDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishListDetailId"), 1L, 1);

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<int>("WishListId")
                        .HasColumnType("int");

                    b.HasKey("WishListDetailId");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("WishListId");

                    b.ToTable("WishListDetails");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.FurnitureRepository", b =>
                {
                    b.Property<int>("RepositoryId")
                        .HasColumnType("int");

                    b.Property<int>("FurnitureSpecificationId")
                        .HasColumnType("int");

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.HasKey("RepositoryId", "FurnitureSpecificationId");

                    b.HasIndex("FurnitureSpecificationId");

                    b.ToTable("FurnitureRepositories");

                    b.HasData(
                        new
                        {
                            RepositoryId = 1,
                            FurnitureSpecificationId = 1,
                            Available = 0
                        },
                        new
                        {
                            RepositoryId = 1,
                            FurnitureSpecificationId = 2,
                            Available = 0
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Import", b =>
                {
                    b.Property<int>("ImportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportId"), 1L, 1);

                    b.Property<int>("RepositoryId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ImportId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Imports");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.ImportDetail", b =>
                {
                    b.Property<int>("ImportDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImportDetailId"), 1L, 1);

                    b.Property<int>("ImportId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ImportDetailId");

                    b.HasIndex("ImportId");

                    b.HasIndex("MaterialId");

                    b.ToTable("ImportDetais");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"), 1L, 1);

                    b.Property<int?>("DefaultSuplierId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaterialPrice")
                        .HasColumnType("int");

                    b.HasKey("MaterialId");

                    b.HasIndex("DefaultSuplierId");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            DefaultSuplierId = 1,
                            Description = "Material Descriptint 1",
                            MaterialName = "Material 1",
                            MaterialPrice = 5
                        },
                        new
                        {
                            MaterialId = 2,
                            DefaultSuplierId = 1,
                            Description = "Material Descriptint 2",
                            MaterialName = "Material 2",
                            MaterialPrice = 4
                        },
                        new
                        {
                            MaterialId = 3,
                            DefaultSuplierId = 1,
                            Description = "Material Descriptint 3",
                            MaterialName = "Material 3",
                            MaterialPrice = 7
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.MaterialRepository", b =>
                {
                    b.Property<int>("RepositoryId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.HasKey("RepositoryId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("MaterialRepositories");

                    b.HasData(
                        new
                        {
                            RepositoryId = 1,
                            MaterialId = 1,
                            Available = 0
                        },
                        new
                        {
                            RepositoryId = 1,
                            MaterialId = 2,
                            Available = 0
                        },
                        new
                        {
                            RepositoryId = 1,
                            MaterialId = 3,
                            Available = 0
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Repository", b =>
                {
                    b.Property<int>("RepositoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepositoryId"), 1L, 1);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RepositoryName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("RepositoryId");

                    b.HasIndex("AddressId")
                        .IsUnique()
                        .HasFilter("[AddressId] IS NOT NULL");

                    b.ToTable("Repositories");

                    b.HasData(
                        new
                        {
                            RepositoryId = 1,
                            AddressId = 1,
                            Capacity = 50.0,
                            CreationDate = new DateTime(2023, 8, 29, 23, 21, 24, 354, DateTimeKind.Local).AddTicks(1920),
                            RepositoryName = "Repository 1"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Suplier", b =>
                {
                    b.Property<int>("SuplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuplierId"), 1L, 1);

                    b.Property<int?>("SuplierAddressId")
                        .HasMaxLength(60)
                        .HasColumnType("int");

                    b.Property<string>("SuplierEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuplierImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuplierName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SuplierPhoneNums")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SuplierId");

                    b.HasIndex("SuplierAddressId")
                        .IsUnique()
                        .HasFilter("[SuplierAddressId] IS NOT NULL");

                    b.ToTable("Supliers");

                    b.HasData(
                        new
                        {
                            SuplierId = 1,
                            SuplierAddressId = 3,
                            SuplierEmail = "suplieremail1@gmail.com",
                            SuplierName = "Suplier 1",
                            SuplierPhoneNums = "012334546677"
                        });
                });

            modelBuilder.Entity("OnlineShopping.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Debit")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("LatestUpdate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Spent")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cbd44045-0ca9-4237-99a1-24050eb8d7fd",
                            Email = "customer1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "customer1",
                            PasswordHash = "AQAAAAEAACcQAAAAEBwU7Zn7BiLGn5y3guGnRzDczwUcbkZyUzmhdYP+SPwUCamBAYIoG4ROng3GEGGncQ==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "17cad0b3-54bc-48d9-b3fb-d09f5a11bb5b",
                            TwoFactorEnabled = false,
                            UserName = "customer1",
                            Avatar = "customer.jpg",
                            CreationDate = new DateTime(2023, 8, 29, 23, 21, 24, 323, DateTimeKind.Local).AddTicks(6341),
                            Debit = 0.0,
                            DoB = new DateTime(2002, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Customer",
                            Gender = "Male",
                            LastName = "Customer",
                            Spent = 0.0,
                            Status = "Activated"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5fbe3b83-9d43-4d5b-bd4a-9e3644924bf9",
                            Email = "assistant1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "assistant1",
                            PasswordHash = "AQAAAAEAACcQAAAAEPPPkbBtKoLrpwFfcJwqFDfreD3pfyo1KYjXbWcw2sHxJwGnz7izrLBqmKbL2ApzDA==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ff5fb428-ae2e-48b3-8b09-1846ee7d8cef",
                            TwoFactorEnabled = false,
                            UserName = "assistant1",
                            Avatar = "assistant.jpg",
                            CreationDate = new DateTime(2023, 8, 29, 23, 21, 24, 323, DateTimeKind.Local).AddTicks(6370),
                            Debit = 0.0,
                            DoB = new DateTime(2002, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Assistant",
                            Gender = "Female",
                            LastName = "Assistant",
                            Spent = 0.0,
                            Status = "Activated"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "99d76af5-a13a-40ef-8f5b-20b6db043d1b",
                            Email = "manager1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "manager1",
                            PasswordHash = "AQAAAAEAACcQAAAAEEJ7Gln/bW6asVktVGb1M9Kl5vNXbUeakE1ilgP0uj/w7ptVGOeMiOk0ksVHDXDzkg==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "351089ff-175f-4e37-a47e-aaef8cda35e3",
                            TwoFactorEnabled = false,
                            UserName = "manager1",
                            Avatar = "manager.jpg",
                            CreationDate = new DateTime(2023, 8, 29, 23, 21, 24, 323, DateTimeKind.Local).AddTicks(6382),
                            Debit = 0.0,
                            DoB = new DateTime(2000, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Manager",
                            Gender = "Male",
                            LastName = "Manager",
                            Spent = 0.0,
                            Status = "Activated"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "29f731f6-82f7-4761-a4a1-6983295c7997",
                            Email = "admin1@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "admin1",
                            PasswordHash = "AQAAAAEAACcQAAAAEL2Q17L4gI0k1O7naEuvB9HjSf0jMV0ZfhvPJXxMQ9L1m56hK+AjLtBJd5vAwkpetQ==",
                            PhoneNumber = "1234567890",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57749cf3-bc56-4b14-93a4-3b721d20e936",
                            TwoFactorEnabled = false,
                            UserName = "admin1",
                            Avatar = "admin.jpg",
                            CreationDate = new DateTime(2023, 8, 29, 23, 21, 24, 323, DateTimeKind.Local).AddTicks(6391),
                            Debit = 0.0,
                            DoB = new DateTime(2001, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Admin",
                            Gender = "Male",
                            LastName = "Admin",
                            Spent = 0.0,
                            Status = "Activated"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineShopping.Models.Customer.Announcement", b =>
                {
                    b.HasOne("OnlineShopping.Models.User", "User")
                        .WithMany("Announcements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineShopping.Models.Customer.Feedback", b =>
                {
                    b.HasOne("OnlineShopping.Models.User", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Funiture.FurnitureSpecification", "FurnitureSpecification")
                        .WithMany("Feedbacks")
                        .HasForeignKey("FurnitureSpecificationId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Purchase.Order", "Order")
                        .WithMany("Feedbacks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("FurnitureSpecification");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineShopping.Models.Customer.UserAddress", b =>
                {
                    b.HasOne("OnlineShopping.Models.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineShopping.Models.Customer.Warranty", b =>
                {
                    b.HasOne("OnlineShopping.Models.Purchase.Order", "Order")
                        .WithMany("Warranties")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.User", "User")
                        .WithMany("Warranties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.CustomizeFurniture", b =>
                {
                    b.HasOne("OnlineShopping.Models.Funiture.Color", "Color")
                        .WithMany("CustomizeFurnitures")
                        .HasForeignKey("ColorId")
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.User", "Customer")
                        .WithMany("CustomizeFurnitures")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Funiture.Category", "Category")
                        .WithMany("CustomizeFurnitures")
                        .HasForeignKey("WoodId")
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Funiture.Wood", "Wood")
                        .WithMany("CustomizeFurnitures")
                        .HasForeignKey("WoodId")
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Color");

                    b.Navigation("Customer");

                    b.Navigation("Wood");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Furniture", b =>
                {
                    b.HasOne("OnlineShopping.Models.Funiture.Category", "Category")
                        .WithMany("Furnitures")
                        .HasForeignKey("CategoryId");

                    b.HasOne("OnlineShopping.Models.Funiture.Collection", "Collection")
                        .WithMany("Furnitures")
                        .HasForeignKey("CollectionId");

                    b.HasOne("OnlineShopping.Models.Funiture.Label", "Label")
                        .WithMany("Furnitures")
                        .HasForeignKey("LabelId");

                    b.Navigation("Category");

                    b.Navigation("Collection");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.FurnitureSpecification", b =>
                {
                    b.HasOne("OnlineShopping.Models.Funiture.Color", "Color")
                        .WithMany("FurnitureSpecifications")
                        .HasForeignKey("ColorId");

                    b.HasOne("OnlineShopping.Models.Funiture.Furniture", "Furniture")
                        .WithMany("FurnitureSpecifications")
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Funiture.Wood", "Wood")
                        .WithMany("FurnitureSpecification")
                        .HasForeignKey("WoodId");

                    b.Navigation("Color");

                    b.Navigation("Furniture");

                    b.Navigation("Wood");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Result", b =>
                {
                    b.HasOne("OnlineShopping.Models.Funiture.CustomizeFurniture", "CustomizeFurniture")
                        .WithOne("Result")
                        .HasForeignKey("OnlineShopping.Models.Funiture.Result", "CustomizeFurnitureId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CustomizeFurniture");
                });

            modelBuilder.Entity("OnlineShopping.Models.Gallery.CustomizeFurnitureAttachment", b =>
                {
                    b.HasOne("OnlineShopping.Models.Funiture.CustomizeFurniture", "CustomizeFurniture")
                        .WithMany("Attachments")
                        .HasForeignKey("CustomizeFurnitureId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CustomizeFurniture");
                });

            modelBuilder.Entity("OnlineShopping.Models.Gallery.FeedbackAttachment", b =>
                {
                    b.HasOne("OnlineShopping.Models.Customer.Feedback", "Feedback")
                        .WithMany("Attachements")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("OnlineShopping.Models.Gallery.FurnitureSpecificationAttachment", b =>
                {
                    b.HasOne("OnlineShopping.Models.Funiture.FurnitureSpecification", "FurnitureSpecification")
                        .WithMany("Attachments")
                        .HasForeignKey("FurnitureSpecificationId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("FurnitureSpecification");
                });

            modelBuilder.Entity("OnlineShopping.Models.Gallery.WarrantyAttachment", b =>
                {
                    b.HasOne("OnlineShopping.Models.Customer.Warranty", "Warranty")
                        .WithMany("Attachments")
                        .HasForeignKey("WarrantyId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.Cart", b =>
                {
                    b.HasOne("OnlineShopping.Models.User", "Customer")
                        .WithOne("Cart")
                        .HasForeignKey("OnlineShopping.Models.Purchase.Cart", "CustomerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.CartDetail", b =>
                {
                    b.HasOne("OnlineShopping.Models.Purchase.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Funiture.FurnitureSpecification", "FurnitureSpecifition")
                        .WithMany("CartDetails")
                        .HasForeignKey("FurnitureSpecificationId")
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("FurnitureSpecifition");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.CustomizeFurnitureOrderDetail", b =>
                {
                    b.HasOne("OnlineShopping.Models.Funiture.CustomizeFurniture", "CustomizeFurniture")
                        .WithMany("CustomizeFurnitureOrderDetails")
                        .HasForeignKey("CustomizeFunitureId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Purchase.Order", "Order")
                        .WithMany("CustomizeFurnitureOrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomizeFurniture");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.FurnitureOrderDetail", b =>
                {
                    b.HasOne("OnlineShopping.Models.Funiture.FurnitureSpecification", "FurnitureSpecification")
                        .WithMany("FurnitureOrderDetails")
                        .HasForeignKey("FurnitureSpecificationId")
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Purchase.Order", "Order")
                        .WithMany("FurnitureOrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("FurnitureSpecification");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.Order", b =>
                {
                    b.HasOne("OnlineShopping.Models.User", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Purchase.Payment", "Payment")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentId")
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.Point", b =>
                {
                    b.HasOne("OnlineShopping.Models.User", "User")
                        .WithOne("Point")
                        .HasForeignKey("OnlineShopping.Models.Purchase.Point", "CustomerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.WishList", b =>
                {
                    b.HasOne("OnlineShopping.Models.User", "Customer")
                        .WithOne("WishList")
                        .HasForeignKey("OnlineShopping.Models.Purchase.WishList", "CustomerId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.WishListDetail", b =>
                {
                    b.HasOne("OnlineShopping.Models.Funiture.Furniture", "Furniture")
                        .WithMany("WishListDetails")
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Purchase.WishList", "WishList")
                        .WithMany("WishListDetails")
                        .HasForeignKey("WishListId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("WishList");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.FurnitureRepository", b =>
                {
                    b.HasOne("OnlineShopping.Models.Funiture.FurnitureSpecification", "FurnitureSpecification")
                        .WithMany("FurnitureRepositories")
                        .HasForeignKey("FurnitureSpecificationId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Warehouse.Repository", "Repository")
                        .WithMany("FurnitureRepositories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("FurnitureSpecification");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Import", b =>
                {
                    b.HasOne("OnlineShopping.Models.Warehouse.Repository", "Repository")
                        .WithMany("Imports")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.User", "User")
                        .WithMany("Imports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.ImportDetail", b =>
                {
                    b.HasOne("OnlineShopping.Models.Warehouse.Import", "Import")
                        .WithMany("ImportDetails")
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Warehouse.Material", "Material")
                        .WithMany("ImportDetails")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Import");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Material", b =>
                {
                    b.HasOne("OnlineShopping.Models.Warehouse.Suplier", "DefaultSuplier")
                        .WithMany("Materials")
                        .HasForeignKey("DefaultSuplierId");

                    b.Navigation("DefaultSuplier");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.MaterialRepository", b =>
                {
                    b.HasOne("OnlineShopping.Models.Warehouse.Material", "Material")
                        .WithMany("MaterialRepositories")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("OnlineShopping.Models.Warehouse.Repository", "Repository")
                        .WithMany("MaterialRepositories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Repository", b =>
                {
                    b.HasOne("OnlineShopping.Models.Address", "Address")
                        .WithOne("Repository")
                        .HasForeignKey("OnlineShopping.Models.Warehouse.Repository", "AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Suplier", b =>
                {
                    b.HasOne("OnlineShopping.Models.Address", "Address")
                        .WithOne("Suplier")
                        .HasForeignKey("OnlineShopping.Models.Warehouse.Suplier", "SuplierAddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("OnlineShopping.Models.Address", b =>
                {
                    b.Navigation("Repository");

                    b.Navigation("Suplier");

                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("OnlineShopping.Models.Customer.Feedback", b =>
                {
                    b.Navigation("Attachements");
                });

            modelBuilder.Entity("OnlineShopping.Models.Customer.Warranty", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Category", b =>
                {
                    b.Navigation("CustomizeFurnitures");

                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Collection", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Color", b =>
                {
                    b.Navigation("CustomizeFurnitures");

                    b.Navigation("FurnitureSpecifications");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.CustomizeFurniture", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("CustomizeFurnitureOrderDetails");

                    b.Navigation("Result")
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Furniture", b =>
                {
                    b.Navigation("FurnitureSpecifications");

                    b.Navigation("WishListDetails");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.FurnitureSpecification", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("CartDetails");

                    b.Navigation("Feedbacks");

                    b.Navigation("FurnitureOrderDetails");

                    b.Navigation("FurnitureRepositories");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Label", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("OnlineShopping.Models.Funiture.Wood", b =>
                {
                    b.Navigation("CustomizeFurnitures");

                    b.Navigation("FurnitureSpecification");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.Order", b =>
                {
                    b.Navigation("CustomizeFurnitureOrderDetails");

                    b.Navigation("Feedbacks");

                    b.Navigation("FurnitureOrderDetails");

                    b.Navigation("Warranties");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.Payment", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OnlineShopping.Models.Purchase.WishList", b =>
                {
                    b.Navigation("WishListDetails");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Import", b =>
                {
                    b.Navigation("ImportDetails");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Material", b =>
                {
                    b.Navigation("ImportDetails");

                    b.Navigation("MaterialRepositories");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Repository", b =>
                {
                    b.Navigation("FurnitureRepositories");

                    b.Navigation("Imports");

                    b.Navigation("MaterialRepositories");
                });

            modelBuilder.Entity("OnlineShopping.Models.Warehouse.Suplier", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("OnlineShopping.Models.User", b =>
                {
                    b.Navigation("Announcements");

                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("CustomizeFurnitures");

                    b.Navigation("Feedbacks");

                    b.Navigation("Imports");

                    b.Navigation("Orders");

                    b.Navigation("Point");

                    b.Navigation("UserAddresses");

                    b.Navigation("Warranties");

                    b.Navigation("WishList")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
